name: build-docs
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: sphinxdoc/sphinx:latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          cd docs
          make clean html
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          # Path of the directory containing the static assets.
          path: docs/_build/html
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.2
