name: build-docs
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: sphinxdoc/sphinx:latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          cd docs
          make clean html
      # - uses: actions/upload-pages-artifact
      #   with:
      #     path: _build
  # deploy:
  #   needs: build-docs
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pages: write # to deploy to Pages
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - uses: action/deploy-pages@v1
